name: Changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run changelog
      - run: git add CHANGELOG.md && git commit -m "Update changelog [skip ci]" || echo "No changes"
      - run: git push
